internalDir: /home/gus/code/maestro/backend/images
servers:
  server1:
    username: gus
    host: localhost
    port: 22
    podmanSocket: /run/user/1000/podman/podman.sock
    identityFile: /home/gus/.ssh/podman_id_ed25519
    remoteDir: /home/gus/code/maestro/backend/server1
