internalDir: /home/raquel/Documentos/maestro/backend/images
servers:
  server1:
    username: raquel
    host: localhost
    podmanSocket: /run/user/1000/podman/podman.sock
    identityFile: /home/raquel/.ssh/podman_id_ed25519
    remoteDir: /home/raquel/Documentos/maestro/backend/server1
